version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo:27017/csvHandler  # Corrected port
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "2703:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge

